name : "Calculator"

on:
  push:
    branches:
      - master 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Change to your required version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
    
      - name: Create tests folder (if needed)
        run: |
         mkdir -p tests
         touch tests/__init__.py

      - name: Run tests
        run: |
          pytest  # Or your preferred test runner